In [108]:
import pandas as pd
import numpy as np
from scipy import stats

In [6]:
df=pd.read_csv("Arrest_Data_from_2010_to_Present.csv")

In [7]:
df.head()

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location
0,4248313,02/24/2015,1310.0,20,Olympic,2022,37,M,H,5.0,Burglary,F,459PC,BURGLARY,5TH,WILTON,"(34.0653, -118.314)"
1,191811472,05/03/2019,1700.0,18,Southeast,1802,23,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)"
2,4254777,02/26/2015,2010.0,19,Mission,1985,22,M,H,6.0,Larceny,M,459.5PC,SHOPLIFTING,8300 VAN NUYS BL,NaN,"(34.2216, -118.4488)"
3,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)"
4,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)"

In [9]:
df["Date_of_Arrest"]=pd.to_datetime(df["Arrest Date"])

In [10]:
df.head()

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,Date_of_Arrest
0,4248313,02/24/2015,1310.0,20,Olympic,2022,37,M,H,5.0,Burglary,F,459PC,BURGLARY,5TH,WILTON,"(34.0653, -118.314)",2015-02-24
1,191811472,05/03/2019,1700.0,18,Southeast,1802,23,F,B,NaN,NaN,M,653.22 PC,NaN,91ST,FIGUEROA,"(33.9543, -118.2827)",2019-05-03
2,4254777,02/26/2015,2010.0,19,Mission,1985,22,M,H,6.0,Larceny,M,459.5PC,SHOPLIFTING,8300 VAN NUYS BL,NaN,"(34.2216, -118.4488)",2015-02-26
3,5614161,04/29/2019,1040.0,8,West LA,842,41,M,H,3.0,Robbery,F,211PC,ROBBERY,11600 WILSHIRE BL,NaN,"(34.0508, -118.4592)",2019-04-29
4,5615197,04/30/2019,615.0,6,Hollywood,663,27,M,O,5.0,Burglary,F,459PC,BURGLARY,LA BREA,LEXINGTON,"(34.0907, -118.3384)",2019-04-30

In [12]:
df["year"]=df["Date_of_Arrest"].dt.year

In [13]:
df_2018=df[df["year"]==2018]

In [14]:
len(df_2018)

104277

In [17]:
df_2018["Area Name"].value_counts()

Central        10951
Hollywood       9715
Rampart         7345
Pacific         6778
77th Street     6259
Van Nuys        6193
Southwest       5927
Newton          5427
N Hollywood     4947
Mission         4357
Olympic         3898
Harbor          3875
Southeast       3601
Hollenbeck      3590
West Valley     3562
Northeast       3452
Devonshire      3146
Topanga         3094
Foothill        3006
West LA         2687
Wilshire        2467
Name: Area Name, dtype: int64

In [27]:
dm=df_2018.Age.rank()

TypeError: rank() got an unexpected keyword argument 'quantile'

In [36]:
x=df_2018[df_2018.Age>df_2018.Age.quantile(0.95)]

In [46]:
x

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,Date_of_Arrest,year,Percentile_rank
2619,5419280,09/11/2018,518.0,1,Central,111,69,M,B,22.0,Driving Under Influence,F,23152(A)VC,DUI ALCOHOL/DRUG W/PRIORS,FIGUEROA,SUNSET,"(34.0627, -118.2463)",2018-09-11,2018,0.992256
4757,5463816,11/02/2018,915.0,16,Foothill,1612,63,M,B,16.0,Narcotic Drug Laws,F,11351.5HS,POSS/PURCHASE COCAINE BASE FOR SALE,PAXTON,BRADLEY,"(34.2749, -118.4246)",2018-11-02,2018,0.973767
6698,182022778,12/20/2018,2025.0,20,Olympic,2031,74,F,A,13.0,Prostitution/Allied,M,647(B)PC,PROSTITUTION,3800 W 8TH ST,NaN,"(34.0599, -118.3139)",2018-12-20,2018,0.997473
6753,5219953,01/31/2018,1730.0,1,Central,135,60,M,B,24.0,Miscellaneous Other Violations,F,594(A)(2)PC,DAMAGE PROPERTY,3RD,SPRING,"(34.0503, -118.247)",2018-01-31,2018,0.954980
6762,5348245,06/23/2018,1100.0,3,Southwest,392,60,M,B,4.0,Aggravated Assault,F,245(A)(1)PC,"ADW, NOT FIREARM, W/GBI",6TH AV,VERNON AV,"(34.0037, -118.3236)",2018-06-23,2018,0.954980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289969,5509593,12/31/2018,1927.0,3,Southwest,392,63,M,B,22.0,Driving Under Influence,M,23152(A)VC,DRUNK DRIVING ALCOHOL/DRUGS,CRENSHAW BL,VERNON AV,"(34.0023, -118.3311)",2018-12-31,2018,0.973767
1289986,5509110,12/30/2018,2040.0,19,Mission,1971,60,M,B,24.0,Miscellaneous Other Violations,M,602(O)(1)PC,REFUSE TO LEAVE PROPERTY UPON REQUEST P.O.,8900 SEPULVEDA BL,NaN,"(34.2337, -118.4703)",2018-12-30,2018,0.954980
1290116,5509394,12/31/2018,1200.0,3,Southwest,363,71,M,B,12.0,Weapon (carry/poss),F,21310PC,CARRY CONCEALED ON PERSON DIRK OR DAGGER,MARTIN LUTHER KI,COLISEUM,"(34.0126, -118.3403)",2018-12-31,2018,0.995066
1290121,5509927,12/31/2018,2355.0,8,West LA,805,71,M,B,22.0,Driving Under Influence,M,23152(F)VC,DUI OF ANY DRUG,SANTA MONICA FY,BEL AIR CR,"(34.1016, -118.4698)",2018-12-31,2018,0.995066
1290308,5509383,12/31/2018,1130.0,15,N Hollywood,1555,76,M,W,24.0,Miscellaneous Other Violations,M,594(B)2APC,DEFACE/DAMAGE PROPERTY <$400,11300 BLIX ST,NaN,"(34.1566, -118.3769)",2018-12-31,2018,0.998211

In [47]:
x['Charge Group Description'].value_counts()

Miscellaneous Other Violations    773
Drunkeness                        492
Liquor Laws                       438
Narcotic Drug Laws                424
Aggravated Assault                400
Driving Under Influence           381
Other Assaults                    370
Disorderly Conduct                208
Larceny                           198
Moving Traffic Violations         121
Sex (except rape/prst)             93
Weapon (carry/poss)                60
Fraud/Embezzlement                 49
Prostitution/Allied                45
Robbery                            40
Against Family/Child               36
Vehicle Theft                      24
Burglary                           24
Gambling                           19
Rape                               19
Homicide                           10
Disturbing the Peace                9
Forgery/Counterfeit                 8
Receive Stolen Property             4
Name: Charge Group Description, dtype: int64

In [61]:
x.loc[: , "Charge Group Description"]

2619              Driving Under Influence
4757                   Narcotic Drug Laws
6698                  Prostitution/Allied
6753       Miscellaneous Other Violations
6762                   Aggravated Assault
                        ...
1289969           Driving Under Influence
1289986    Miscellaneous Other Violations
1290116               Weapon (carry/poss)
1290121           Driving Under Influence
1290308    Miscellaneous Other Violations
Name: Charge Group Description, Length: 5120, dtype: object

In [68]:
Vehicle_Theft=24
Robbery=40
Burglary=24
Receive_Stolen_Property=4
def summ(a,b,c,d):
     return a+b+c+d
total_arrestee=summ(Vehicle_Theft,Robbery,Burglary,Receive_Stolen_Property)

In [69]:
total_arrestee

92

In [70]:
df_2018

,Report ID,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,Charge Group Code,Charge Group Description,Arrest Type Code,Charge,Charge Description,Address,Cross Street,Location,Date_of_Arrest,year,Percentile_rank
165,5213460,01/24/2018,1930.0,6,Hollywood,668,29,M,H,10.0,Fraud/Embezzlement,F,530.5(A)PC,GET CREDIT/ETC OTHER'S ID,ST ANDREWS,FOUNTAIN,"(34.0949, -118.3109)",2018-01-24,2018,0.398827
166,5257944,03/15/2018,310.0,7,Wilshire,743,33,F,O,1.0,Homicide,F,191.5(B)PC,VEH MANSLAUGHTR/OPER VESSEL DUI & DUR FEL,OLYMPIC,MASSELIN,"(34.0574, -118.3547)",2018-03-15,2018,0.517492
167,5328813,06/01/2018,1800.0,3,Southwest,356,44,F,B,16.0,Narcotic Drug Laws,F,11379(A)HS,TRANSPORT/SELL CONTROLLED SUBSTANCE,1600 W 36TH PL,NaN,"(34.0219, -118.3061)",2018-06-01,2018,0.747413
168,5336331,06/10/2018,200.0,13,Newton,1364,23,M,H,12.0,Weapon (carry/poss),F,25400(A)2PC,CARRYING CONCEALED WEAPON UPON PERSON,1200 E 50TH ST,NaN,"(33.998, -118.2543)",2018-06-10,2018,0.180342
169,5360731,07/07/2018,2330.0,18,Southeast,1832,32,M,B,12.0,Weapon (carry/poss),F,29800(A)1PC,POSS F/ARM BY CONVICTED FELON/ADDICT/ETC,10700 S MAIN ST,NaN,"(33.9392, -118.2739)",2018-07-07,2018,0.489777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1290652,5509442,12/31/2018,1400.0,19,Mission,1963,36,M,H,8.0,Other Assaults,F,422(A)PC,TERRORIZE CAUSING FEAR,14700 PLUMMER ST,NaN,"(34.2454, -118.4505)",2018-12-31,2018,0.593026
1290661,5509487,12/31/2018,1545.0,1,Central,155,55,M,B,8.0,Other Assaults,F,422(A)PC,TERRORIZE CAUSING FEAR,5TH ST,MAPLE,"(34.0454, -118.2466)",2018-12-31,2018,0.903051
1290666,5509344,12/31/2018,720.0,11,Northeast,1133,25,M,H,6.0,Larceny,M,490.2PC,PETTY THEFT,3100 GLENDALE BL,NaN,"(34.1119, -118.2529)",2018-12-31,2018,0.252002
1290673,5509947,12/31/2018,2320.0,4,Hollenbeck,408,23,M,H,16.0,Narcotic Drug Laws,F,11378HS,POSSESSION CONTROLLED SUBSTANCE FOR SALE,HUNTINGTON,ROSEMEAD,"(34.0872, -118.176)",2018-12-31,2018,0.180342
1290693,5509405,12/31/2018,1200.0,19,Mission,1921,28,F,H,7.0,Vehicle Theft,F,10851(A)VC,TAKE VEHICLE W/O OWNER'S CONSENT,15100 POLK ST,NaN,"(34.3009, -118.4696)",2018-12-31,2018,0.364855

In [ ]:
y=df_2018["Charge Group Description"].drop[]

In [73]:
df_2018["Charge Group Description"].value_counts()

Miscellaneous Other Violations    17023
Narcotic Drug Laws                10697
Aggravated Assault                 9231
Driving Under Influence            8918
Other Assaults                     7907
Larceny                            5129
Drunkeness                         3769
Moving Traffic Violations          3565
Liquor Laws                        3481
Weapon (carry/poss)                3396
Vehicle Theft                      3257
Prostitution/Allied                2970
Robbery                            2787
Disorderly Conduct                 2536
Burglary                           1958
Sex (except rape/prst)             1179
Fraud/Embezzlement                 1061
Against Family/Child                923
Receive Stolen Property             455
Forgery/Counterfeit                 415
Rape                                315
Homicide                            274
Non-Criminal Detention              198
Gambling                            175
Disturbing the Peace                 98
Pre-Delinquency                      72
Federal Offenses                     25
Name: Charge Group Description, dtype: int64

In [83]:
y=df_2018[df_2018["Charge Group Description"]=="Non-Criminal Detention"]
#y=df_2018[df_2018["Charge Group Description"]=="Pre-Delinquency"]

In [100]:
new_df=df_2018.drop(df_2018[df_2018["Charge Group Description"]=="Non-Criminal Detention"].index)

new_df_2018=new_df.drop(new_df[new_df["Charge Group Description"]=="Pre-Delinquency"].index)

In [101]:
new_df_2018["Charge Group Description"].value_counts()

Miscellaneous Other Violations    17023
Narcotic Drug Laws                10697
Aggravated Assault                 9231
Driving Under Influence            8918
Other Assaults                     7907
Larceny                            5129
Drunkeness                         3769
Moving Traffic Violations          3565
Liquor Laws                        3481
Weapon (carry/poss)                3396
Vehicle Theft                      3257
Prostitution/Allied                2970
Robbery                            2787
Disorderly Conduct                 2536
Burglary                           1958
Sex (except rape/prst)             1179
Fraud/Embezzlement                 1061
Against Family/Child                923
Receive Stolen Property             455
Forgery/Counterfeit                 415
Rape                                315
Homicide                            274
Gambling                            175
Disturbing the Peace                 98
Federal Offenses                     25
Name: Charge Group Description, dtype: int64

In [112]:
avg_age=new_df_2018.groupby(["Charge Group Description"]).mean()
print(avg_age.head)

<bound method NDFrame.head of                                    Report ID         Time    Area ID  \
Charge Group Description
Against Family/Child            5.355391e+06  1372.403034  11.253521
Aggravated Assault              5.371929e+06  1301.963276  10.519120
Burglary                        5.527964e+06  1223.551583  10.269152
Disorderly Conduct              1.546133e+08  1223.168770   4.675079
Disturbing the Peace            1.169235e+08  1303.775510   9.836735
Driving Under Influence         5.503826e+06  1193.650706  11.211258
Drunkeness                      1.708722e+08  1523.112762   8.333510
Federal Offenses                5.328202e+06  1607.200000  11.360000
Forgery/Counterfeit             2.181846e+07  1368.096386   9.296386
Fraud/Embezzlement              1.214087e+07  1396.926484  10.893497
Gambling                        1.482961e+08  1691.851429  13.342857
Homicide                        5.343437e+06  1196.149635  11.145985
Larceny                         2.638031e+07  1523.326053  10.214077
Liquor Laws                     1.791047e+08  1462.085082   6.513071
Miscellaneous Other Violations  4.305876e+07  1383.876226   9.505963
Moving Traffic Violations       6.282647e+06  1404.854698  10.040393
Narcotic Drug Laws              3.088710e+07  1400.128167   9.438067
Other Assaults                  6.262036e+06  1367.379917  10.160364
Prostitution/Allied             7.718441e+07  1280.003368  11.551852
Rape                            5.348261e+06  1267.647619  10.015873
Receive Stolen Property         6.128102e+06  1376.630769   9.747253
Robbery                         5.353295e+06  1410.505562  10.025117
Sex (except rape/prst)          4.675985e+07  1376.081425   9.824427
Vehicle Theft                   5.347520e+06  1307.979736  11.343261
Weapon (carry/poss)             7.417651e+06  1498.749411  10.679918

                                Reporting District        Age  \
Charge Group Description
Against Family/Child                   1167.991333  35.539545
Aggravated Assault                     1098.054382  34.434622
Burglary                               1074.289581  30.391216
Disorderly Conduct                      520.746451  41.229890
Disturbing the Peace                   1029.510204  39.010204
Driving Under Influence                1168.731891  34.953353
Drunkeness                              884.585036  43.905015
Federal Offenses                       1177.960000  34.080000
Forgery/Counterfeit                     977.645783  34.265060
Fraud/Embezzlement                     1136.788878  35.615457
Gambling                               1375.702857  41.308571
Homicide                               1161.368613  30.470803
Larceny                                1068.677520  33.776565
Liquor Laws                             696.171790  42.483482
Miscellaneous Other Violations          997.829936  35.537684
Moving Traffic Violations              1049.597475  33.874614
Narcotic Drug Laws                      991.332336  36.303356
Other Assaults                         1062.999241  34.091311
Prostitution/Allied                    1197.198990  30.006061
Rape                                   1046.403175  35.168254
Receive Stolen Property                1022.828571  31.791209
Robbery                                1050.120919  27.182992
Sex (except rape/prst)                 1028.301951  37.029686
Vehicle Theft                          1182.253301  29.821615
Weapon (carry/poss)                    1115.563310  30.174323

                                Charge Group Code    year  Percentile_rank
Charge Group Description
Against Family/Child                         15.0  2018.0         0.521975
Aggravated Assault                            4.0  2018.0         0.485224
Burglary                                      5.0  2018.0         0.393976
Disorderly Conduct                           20.0  2018.0         0.636938
Disturbing the Peace                         19.0  2018.0         0.586214
Driving Under Influence                      22.0  2018.0         0.500590
Drunkeness                                   18.0  2018.0         0.679375
Federal Offenses                             25.0  2018.0         0.504992
Forgery/Counterfeit                           9.0  2018.0         0.492394
Fraud/Embezzlement                           10.0  2018.0         0.523238
Gambling                                     21.0  2018.0         0.634229
Homicide                                      1.0  2018.0         0.376121
Larceny                                       6.0  2018.0         0.468353
Liquor Laws                                  17.0  2018.0         0.644810
Miscellaneous Other Violations               24.0  2018.0         0.510232
Moving Traffic Violations                    23.0  2018.0         0.477258
Narcotic Drug Laws                           16.0  2018.0         0.535272
Other Assaults                                8.0  2018.0         0.476336
Prostitution/Allied                          13.0  2018.0         0.373049
Rape                                          2.0  2018.0         0.494810
Receive Stolen Property                      11.0  2018.0         0.433267
Robbery                                       3.0  2018.0         0.305060
Sex (except rape/prst)                       14.0  2018.0         0.532483
Vehicle Theft                                 7.0  2018.0         0.384591
Weapon (carry/poss)                          12.0  2018.0         0.385933  >

In [117]:
z_score=stats.zscore(avg_age['Age'])
z_score

array([ 0.15473346, -0.11167656, -1.08659029,  1.52674355,  0.99155085,
        0.01339552,  2.17174816, -0.19718027, -0.15256004,  0.17303679,
        1.54571468, -1.06740082, -0.27034217,  1.8289996 ,  0.15428483,
       -0.24670122,  0.33889745, -0.19445294, -1.17945575,  0.06521076,
       -0.74903519, -1.86013121,  0.51402431, -1.22392779, -1.13888574])

In [116]:
abs(max(z_score))

2.1717481576567237